server:
  port: 8080
spring:
  main:
    lazy-initialization: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5  # Giảm xuống 5 để tiết kiệm RAM
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000
  threads:
    virtual:
      enabled: true
  data:
    web:
      pageable:
        serialization-mode: via-dto
        one-indexed-parameters: true
  servlet:
    multipart:
      max-file-size: 10MB # Lưu ý: Cẩn thận nếu nhiều người up file 10MB cùng lúc server 256MB có thể tràn RAM
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate # An toàn cho Production. Nếu bạn CỐ TÌNH muốn nó tự tạo bảng, hãy để 'update', nhưng sau khi tạo xong phải đổi lại thành 'validate'
    show-sql: false # BẮT BUỘC TẮT
    properties:
      hibernate:
        default_batch_fetch_size: 20
        format_sql: false # BẮT BUỘC TẮT
        highlight_sql: false # BẮT BUỘC TẮT
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
  web:
    error:
      include-message: always 

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

# Đã đưa tất cả về INFO để bảo vệ RAM và CPU
logging:
  level:
    root: INFO 
    web: INFO 
    org.springframework.web: INFO 
    org.springframework.security: INFO 
    com.photocopy.backend: INFO # Giả sử đây là package của bạn
    org.hibernate.orm.results: INFO 

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  refresh-token: ${GOOGLE_REFRESH_TOKEN}

supabase:
  s3:
    endpoint: ${SUPABASE_S3_ENDPOINT}
    access-key: ${SUPABASE_S3_ACCESS_KEY}
    secret-key: ${SUPABASE_S3_SECRET_KEY}
    buckets:
      products: products
      orders: orders
    region: ${SUPABASE_S3_REGION}
    storage:
      public-url-prefix: ${SUPABASE_S3_PUBLIC_URL_PREFIX}
app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}